app/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime, timedelta
from flask import current_app
import jwt

@login_manager.user_loader
def load_user(user_id):

    return User.query.get(int(user_id))

class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(300))

    def generate_auth_token(self, timeline= 900):

        payload = {
            'exp': datetime.utcnow() + timedelta(seconds=timeline),
            'iat': datetime.utcnow(),
            'sub': self.id
        }

        return jwt.encode(payload, current_app.config['SECRET_KEY'], algorithm='HS256')
    
    

    @staticmethod
    def verify_token(token, secret_key):

        try:

            return jwt.decode(token, secret_key, algorithms=["HS256"])

        except:

            return None

app/__init__.py
from flask import Flask
from config import environment_config

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()

login_manager = LoginManager()

from app.models import User


migrate = Migrate()


def create_app(env_config: str) ->Flask:

    app = Flask(__name__)

    app.config.from_object(environment_config[env_config])

    # flask ported service registration

    db.init_app(app=app)

    migrate.init_app(app=app, db=db)

    login_manager.login_view = "auth.login"

    login_manager.init_app(app=app)

    # partial initialization

    environment_config[env_config].init_app(app=app)

    # blueprint registration

    from app.main import main_bp
    from app.auth import auth_bp
    from app.api import api_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp, url_prefix="/auth")

    app.register_blueprint(api_bp, url_prefix="/api")
    
    return app

app/api/__init__.py
from flask import Blueprint

api_bp =Blueprint("api", __name__)

from app.api.views import *
from app.api.errors import *

app/api/auth.py
from flask_httpauth import HTTPTokenAuth, HTTPBasicAuth
from app.models import User
from flask import current_app, jsonify
from werkzeug.security import check_password_hash

token_auth = HTTPTokenAuth()
basic_Auth = HTTPBasicAuth()


@basic_Auth.verify_password
def verify_password(email, password):

    user = User.query.filter_by(email = email).first()

    if not user or  not check_password_hash(user.password, password):

        return None
    
    return user

@token_auth.verify_token
def verify_token(token):

    jwt = User.verify_token(token, current_app.config['SECRET_KEY'])

    if jwt is None:

        return None
    
    return User.query.get(jwt["sub"])

@basic_Auth.error_handler
def basic_auth_error(status):

    return jsonify({'message': 'Invalid credentials'}), status


@token_auth.error_handler
def token_auth_error(status):

    return jsonify({'message': 'Unauthorized'}), status

app/api/views.py
from app.api import api_bp
from app.api.auth import basic_Auth, token_auth
from flask import jsonify
from app.models import User

@api_bp.route('/login')
@basic_Auth.login_required
def login():

    current_user = basic_Auth.current_user()


    token = current_user.generate_auth_token()

    return jsonify({'token': token})


@api_bp.route('/users')
@token_auth.login_required
def get_users():

    users = {}

    for userset in User.query.all():

        users['email'] = userset.email
        users['name'] = userset.name

    return jsonify({'users': users})

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

from .views import *

app/main/views.py
from app.main import main_bp
from flask import request
from flask_login import login_required

@main_bp.route('/')
@login_required
def home():

    return "welcome to flask 101"

@main_bp.route('/profile')
@login_required
def profile():

    return "profile page"

main.py
""" A ------ > B ------- C
    if B fails ----- D


    Message Queues 
"""
from redis import Redis
from rq import Queue
from job import expensive_call, on_success_count, do_something_else

redis_db_connection = Redis(host="localhost", port=6379)

job_queue = Queue(connection=redis_db_connection)



"""

    job_timeout
    result_ttl
    ttl
    failure_ttl
    depends_on
    job_id
    at_front
    description >> message describing what the function does
    on_success >>
    on_failure >>
    on_stopped >>

    args, 

    kwargs >>
"""
job= job_queue.enqueue(
    expensive_call,
    args=("https://www.google.com",),
    on_success = on_success_count
)

job_2 = job_queue.enqueue(do_something_else, depends_on = job)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.home') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="{{ url_for('auth.login') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        <form method="POST" action="{{ url_for('auth.signup') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}